package com.abstractlabs.toe.block;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.renderer.texture.IIconRegister;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Blocks;
import net.minecraft.util.IIcon;
import net.minecraft.world.World;

import com.abstractlabs.toe.reference.Reference;
import com.abstractlabs.toe.structures.UFO;

import cpw.mods.fml.relauncher.Side;
import cpw.mods.fml.relauncher.SideOnly;

public class BlockTester extends BlockToe {
	public static IIcon side;
	
	public BlockTester() {
		super(Material.sponge, Block.soundTypeCloth, "tester");
		setHardness(1);
	}
    
	public void registerBlockIcons(IIconRegister ir) {
		side = ir.registerIcon(Reference.MOD_ID + ":tester");
	}
	
	@SideOnly(Side.CLIENT)
    public IIcon getIcon(int side, int meta) {
        return Blocks.brick_block.getIcon(side, meta);
    }
	
	public boolean onBlockActivated(World world, int x, int y, int z, EntityPlayer player, int par6, float par7, float par8, float par9) {
		//Shrine.build(world, x, y, z, Blocks.stonebrick, 0, Blocks.stone_slab, 5, Blocks.stained_glass, 15, Blocks.stained_glass_pane, 15, Blocks.flowing_lava, 0);
		//ArenaPyramid.build(world, x, y, z, Blocks.emerald_block, 0, ToeBlocks.quicksand, 0, Blocks.bedrock, 0, 30);
		//WizardTower.build(world, x, y, z, Blocks.stonebrick, 0, Blocks.stonebrick, 2, Blocks.stonebrick, 3, Blocks.planks, 5, Blocks.stained_glass, 15, Blocks.stone_brick_stairs, 0, Blocks.stone_slab, 5, Blocks.cobblestone_wall, 0, Blocks.wool, 11);
		//Bank.build(world, x, y, z, Blocks.stonebrick, 0, Blocks.planks, 5, Blocks.stone_brick_stairs, 0, Blocks.stone_slab, 5, Blocks.cobblestone_wall, 0, Blocks.fence, 0, Blocks.redstone_lamp, 0, Blocks.wooden_slab, 5);
		UFO.build(world, x, y, z, Blocks.quartz_block, 0, Blocks.obsidian, 5, Blocks.glowstone, 0);
		
		//Block dirt = Blocks.grass;
		
//		world.setBlock(x+0, y+0, z+0, Blocks.iron_block, 0, 2);
//		world.setBlock(x+0, y+0, z+6, Blocks.stone_brick_stairs, 0, 2);
//		world.setBlock(x+0, y+0, z+7, Blocks.stone_brick_stairs, 0, 2);
//		world.setBlock(x+0, y+0, z+8, Blocks.stone_brick_stairs, 0, 2);
//		world.setBlock(x+1, y+0, z+5, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+1, y+0, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+1, y+0, z+7, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+1, y+0, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+1, y+0, z+9, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+1, y+1, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+1, y+1, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+1, y+2, z+5, Blocks.torch, 5, 2);
//		world.setBlock(x+1, y+2, z+9, Blocks.torch, 5, 2);
//		world.setBlock(x+2, y+0, z+3, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+2, y+0, z+4, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+2, y+0, z+5, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+2, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+2, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+2, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+2, y+0, z+9, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+2, y+0, z+10, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+2, y+0, z+11, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+2, y+1, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+1, z+4, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+1, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+1, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+1, z+10, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+1, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+2, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+2, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+3, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+3, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+4, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+4, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+2, y+5, z+3, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+5, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+6, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+7, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+8, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+9, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+2, y+5, z+11, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+3, y+0, z+2, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+3, y+0, z+3, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+3, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+3, y+0, z+11, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+3, y+0, z+12, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+3, y+1, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+1, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+1, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+1, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+2, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+2, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+3, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+3, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+4, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+4, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+3, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+3, y+5, z+3, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+3, y+5, z+4, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+5, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+9, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+10, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+3, y+5, z+11, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+3, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+0, z+2, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+4, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+4, y+0, z+12, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+4, y+1, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+4, y+1, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+4, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+4, y+5, z+4, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+4, y+5, z+10, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+4, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+4, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+6, z+5, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+6, z+6, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+6, z+7, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+6, z+8, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+4, y+6, z+9, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+5, y+0, z+1, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+5, y+0, z+2, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+5, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+5, y+0, z+12, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+5, y+0, z+13, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+5, y+1, z+1, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+1, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+1, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+1, z+13, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+2, z+1, Blocks.torch, 5, 2);
//		world.setBlock(x+5, y+2, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+2, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+2, z+13, Blocks.torch, 5, 2);
//		world.setBlock(x+5, y+3, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+3, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+4, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+4, z+5, Blocks.redstone_lamp, 0, 2);
//		world.setBlock(x+5, y+4, z+9, Blocks.redstone_lamp, 0, 2);
//		world.setBlock(x+5, y+4, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+5, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+5, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+5, y+5, z+5, Blocks.fence, 0, 2);
//		world.setBlock(x+5, y+5, z+9, Blocks.fence, 0, 2);
//		world.setBlock(x+5, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+5, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+5, y+6, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+5, y+6, z+5, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+5, y+6, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+5, y+6, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+5, y+6, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+5, y+6, z+9, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+5, y+6, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+6, y+0, z+0, Blocks.stone_brick_stairs, 2, 2);
//		world.setBlock(x+6, y+0, z+1, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+0, z+2, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+0, z+7, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+0, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+12, Blocks.planks, 5, 2);
//		world.setBlock(x+6, y+0, z+13, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+0, z+14, Blocks.stone_brick_stairs, 3, 2);
//		world.setBlock(x+6, y+1, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+1, z+7, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+6, y+1, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+6, y+2, z+6, Blocks.fence, 0, 2);
//		world.setBlock(x+6, y+2, z+8, Blocks.fence, 0, 2);
//		world.setBlock(x+6, y+3, z+6, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+6, y+3, z+7, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+6, y+3, z+8, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+6, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+6, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+6, y+6, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+6, y+6, z+5, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+6, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+6, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+6, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+6, z+9, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+6, y+6, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+7, y+0, z+0, Blocks.stone_brick_stairs, 2, 2);
//		world.setBlock(x+7, y+0, z+1, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+7, y+0, z+2, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+7, y+0, z+7, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+7, y+0, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+7, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+12, Blocks.planks, 5, 2);
//		world.setBlock(x+7, y+0, z+13, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+7, y+0, z+14, Blocks.stone_brick_stairs, 3, 2);
//		world.setBlock(x+7, y+1, z+6, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+7, y+1, z+8, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+7, y+3, z+6, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+7, y+3, z+7, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+7, y+3, z+8, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+7, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+7, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+7, y+6, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+7, y+6, z+5, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+6, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+6, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+6, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+6, z+9, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+7, y+6, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+8, y+0, z+0, Blocks.stone_brick_stairs, 2, 2);
//		world.setBlock(x+8, y+0, z+1, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+0, z+2, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+0, z+7, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+0, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+12, Blocks.planks, 5, 2);
//		world.setBlock(x+8, y+0, z+13, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+0, z+14, Blocks.stone_brick_stairs, 3, 2);
//		world.setBlock(x+8, y+1, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+1, z+7, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+8, y+1, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+8, y+2, z+6, Blocks.fence, 0, 2);
//		world.setBlock(x+8, y+2, z+8, Blocks.fence, 0, 2);
//		world.setBlock(x+8, y+3, z+6, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+8, y+3, z+7, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+8, y+3, z+8, Blocks.stone_slab, 5, 2);
//		world.setBlock(x+8, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+8, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+8, y+6, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+8, y+6, z+5, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+6, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+6, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+6, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+6, z+9, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+8, y+6, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+9, y+0, z+1, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+9, y+0, z+2, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+9, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+9, y+0, z+12, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+9, y+0, z+13, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+9, y+1, z+1, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+1, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+1, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+1, z+13, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+2, z+1, Blocks.torch, 5, 2);
//		world.setBlock(x+9, y+2, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+2, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+2, z+13, Blocks.torch, 5, 2);
//		world.setBlock(x+9, y+3, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+3, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+4, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+4, z+5, Blocks.redstone_lamp, 0, 2);
//		world.setBlock(x+9, y+4, z+9, Blocks.redstone_lamp, 0, 2);
//		world.setBlock(x+9, y+4, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+9, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+9, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+9, y+5, z+5, Blocks.fence, 0, 2);
//		world.setBlock(x+9, y+5, z+9, Blocks.fence, 0, 2);
//		world.setBlock(x+9, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+9, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+9, y+6, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+9, y+6, z+5, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+9, y+6, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+9, y+6, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+9, y+6, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+9, y+6, z+9, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+9, y+6, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+0, z+2, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+10, y+0, z+3, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+11, Blocks.planks, 5, 2);
//		world.setBlock(x+10, y+0, z+12, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+10, y+1, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+10, y+1, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+10, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+5, z+3, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+10, y+5, z+4, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+10, y+5, z+10, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+10, y+5, z+11, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+10, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+6, z+5, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+6, z+6, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+6, z+7, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+6, z+8, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+10, y+6, z+9, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+11, y+0, z+2, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+11, y+0, z+3, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+11, y+0, z+4, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+5, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+9, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+10, Blocks.planks, 5, 2);
//		world.setBlock(x+11, y+0, z+11, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+11, y+0, z+12, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+11, y+1, z+2, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+1, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+1, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+1, z+12, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+2, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+2, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+3, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+3, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+4, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+4, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+11, y+5, z+2, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+11, y+5, z+3, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+11, y+5, z+4, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+5, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+6, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+7, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+8, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+9, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+10, Blocks.wooden_slab, 13, 2);
//		world.setBlock(x+11, y+5, z+11, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+11, y+5, z+12, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+0, z+3, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+12, y+0, z+4, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+12, y+0, z+5, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+12, y+0, z+6, Blocks.planks, 5, 2);
//		world.setBlock(x+12, y+0, z+7, Blocks.planks, 5, 2);
//		world.setBlock(x+12, y+0, z+8, Blocks.planks, 5, 2);
//		world.setBlock(x+12, y+0, z+9, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+12, y+0, z+10, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+12, y+0, z+11, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+12, y+1, z+3, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+1, z+4, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+1, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+1, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+1, z+10, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+1, z+11, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+2, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+2, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+3, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+3, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+4, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+4, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+12, y+5, z+3, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+4, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+5, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+6, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+7, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+8, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+9, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+10, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+12, y+5, z+11, Blocks.wooden_slab, 5, 2);
//		world.setBlock(x+13, y+0, z+5, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+13, y+0, z+6, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+13, y+0, z+7, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+13, y+0, z+8, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+13, y+0, z+9, Blocks.stonebrick, 0, 2);
//		world.setBlock(x+13, y+1, z+5, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+13, y+1, z+9, Blocks.cobblestone_wall, 0, 2);
//		world.setBlock(x+13, y+2, z+5, Blocks.torch, 5, 2);
//		world.setBlock(x+13, y+2, z+9, Blocks.torch, 5, 2);
//		world.setBlock(x+14, y+0, z+6, Blocks.stone_brick_stairs, 1, 2);
//		world.setBlock(x+14, y+0, z+7, Blocks.stone_brick_stairs, 1, 2);
//		world.setBlock(x+14, y+0, z+8, Blocks.stone_brick_stairs, 1, 2);
//		world.setBlock(x+14, y+6, z+14, Blocks.iron_block, 0, 2);

		
		return true;
	}
}